### ISSUE TITLE
Gems installed from git aren't available to tests

### ISSUE THREAD

**Issue by cmparkinson** [test-kitchen/busser-serverspec#30]
Gems in the serverspec Gemfile that are installed from git aren't available to tests.

For example, a Gemfile containing:
`gem 'dummy_gem', git: 'git@github.com:test/dummy_gem.git'`

And a test that requires said gem:
`require 'dummy_gem'`

Will result in rubygems raising a LoadError exception.  I can see from the bundler output that the gem is in fact getting installed; it's just not available.

**Comment by cl-lab-k** [comment]
reproduced.

**Comment by cl-lab-k** [comment]
```ruby
source 'https://rubygems.org'
gem 'serverspec', '< 3.0'
gem 'infrataster', git: 'https://github.com/ryotarai/infrataster.git'
```

```sh
vagrant@default-ubuntu-1404:~$ ls /tmp/verifier/gems/{gems,bundler/gems}
/tmp/verifier/gems/bundler/gems:
infrataster-ffa1130fdcb7

/tmp/verifier/gems/gems:
bundler-1.10.4           net-scp-1.2.1             rspec-mocks-3.3.0
busser-0.7.1             net-ssh-2.9.2             rspec-support-3.3.0
busser-serverspec-0.5.7  net-ssh-gateway-1.2.0     serverspec-2.18.0
capybara-2.4.4           nokogiri-1.6.6.2          specinfra-2.36.0
cliver-0.3.2             poltergeist-1.6.0         thor-0.19.0
diff-lcs-1.2.5           rack-1.6.2                thor-0.19.1
faraday-0.9.1            rack-test-0.6.3           websocket-driver-0.5.4
mime-types-2.6.1         rspec-3.3.0               websocket-extensions-0.1.2
mini_portile-0.6.2       rspec-core-3.3.0          xpath-2.0.0
multi_json-1.11.1        rspec-expectations-3.3.0
multipart-post-2.0.0     rspec-its-1.2.0
vagrant@default-ubuntu-1404:~$ 
```

**Comment by cl-lab-k** [comment]
workaround:
```ruby
Dir.glob( File.join( ENV['GEM_HOME'], 'bundler', 'gems', 'infrataster-*', 'lib' ) ).each { |p| $:.push p }
require 'infrataster'
```

**Comment by cl-lab-k** [comment]
you can use `shell verifer` instead of `busser`, it lets `serverspec` run on local system.

* https://github.com/test-kitchen/test-kitchen/pull/741 (it has been merged TK 1.5)
* https://rubygems.org/gems/kitchen-verifier-shell (if you use TK 1.4, install gem)

here is my `shell verifer` and `serverspec` example:
https://github.com/cl-lab-k/apache2-take/tree/shell_verifier

I have no plan to make any drastic changes to `busser-serverspec`.
And I think `shell-verifier` + `serverspec` is better choice for testing cookbooks than `busser` verifier + `busser-serverspec`.
So I am preparing the document for translation from`busser` verifier + `busser-serverspec` to `shell-verifier` + `serverspec`.
If the document is prepared, I will put link to it in README.

**Comment by cl-lab-k** [comment]
https://github.com/test-kitchen/busser-serverspec#-notice

**Comment by Poohblah** [comment]
Dropping busser and switching to the shell verifier turned out to be far more work than I was hoping for, so I was able to add the following to my spec_helper to work around this issue:

```
# save the current load path
old_load_path = $:.dup
# use bundler and the Gemfile to generate a new load path
# (generating a new load path is a side effect of Bundler.setup, not its main purpose)
Dir.chdir(File.dirname(__FILE__)) { Bundler.setup }
# append the original load path to the new one
old_load_path.each { |d| $:.unshift d }
```
