### ISSUE TITLE
Unable to override rspec_opts

### ISSUE THREAD

**Issue by nicholaskey-okta** [test-kitchen/busser-serverspec#35]
It seems that there's way to override rspec_opts. By default it is running with "--color" and "--format documentation".

Is there a way to disable color and execute in format json and documentation?

I've tried adding a .rspec file in the test directory but Test Kitchen doesn't pick that up. I've also tried to move the .rspec file into suite/serverspec directory and still the busser is running with --color and --format documentation.

Any ideas how to disable the color and format it in json and documentation?

Thanks!

**Comment by nicholaskey-okta** [comment]
related to https://github.com/test-kitchen/busser-serverspec/issues/36

**Comment by xmik** [comment]
You can do it in `test/integration/default/serverspec/spec_helper.rb`
```ruby
RSpec.configure do |c|
  c.color = false
  # and so on
end
```

**Comment by cl-lab-k** [comment]
you can use `shell verifer` instead of `busser`, it lets `serverspec` run with any options.

* https://github.com/test-kitchen/test-kitchen/pull/741 (it has been merged TK 1.5)
* https://rubygems.org/gems/kitchen-verifier-shell (if you use TK 1.4, install gem)

here is my `shell verifer` and `serverspec` example:
https://github.com/cl-lab-k/apache2-take/tree/shell_verifier

I have no plan to make any drastic changes to `busser-serverspec`.
And I think `shell-verifier` + `serverspec` is better choice for testing cookbooks than `busser` verifier + `busser-serverspec`.
So I am preparing the document for translation from`busser` verifier + `busser-serverspec` to `shell-verifier` + `serverspec`.
If the document is prepared, I will put link to it in README.

**Comment by cl-lab-k** [comment]
https://github.com/test-kitchen/busser-serverspec#-notice

**Comment by pkazi** [comment]
Can anyone has achieved this ?
I want to outout kitchen test results in html and attach to CI build.

**Comment by pkazi** [comment]
@cl-lab-k  Can u redirect me to the way how this can be achieved with this verifier only.?

We really want to have this report generated.
