### ISSUE TITLE
configure serverspec rspec options, ruby_opts and pattern

### ISSUE THREAD

**Issue by neillturner** [test-kitchen/busser-serverspec#36]
I would like to be able to configure the rspec_opts, ruby_ops and pattern as in the following code snippet. There are different standards for specifying rspec files. specifically ansible_spec puts then in a different place. It would be good if this was configurable so folks are not forced to put them in test/integration/... 
   
t.rspec_path = rspec_bin if rspec_bin
  t.rspec_opts = [
    '--color',
    '--format documentation',
    "--default-path #{base_path}",
  ]
  t.ruby_opts = "-I#{base_path}"
  t.pattern = "#{base_path}/**/*_spec.rb"

If i knew how to configure a busser plugin then i could write a PR request

**Comment by nicholaskey-okta** [comment]
related to https://github.com/test-kitchen/busser-serverspec/issues/35

**Comment by cl-lab-k** [comment]
related to https://github.com/test-kitchen/busser/issues/29

**Comment by cl-lab-k** [comment]
you can use `shell verifer` instead of `busser`, it lets `serverspec` run with any options.

* https://github.com/test-kitchen/test-kitchen/pull/741 (it has been merged TK 1.5)
* https://rubygems.org/gems/kitchen-verifier-shell (if you use TK 1.4, install gem)

here is my `shell verifer` and `serverspec` example:
https://github.com/cl-lab-k/apache2-take/tree/shell_verifier

I have no plan to make any drastic changes to `busser-serverspec`.
And I think `shell-verifier` + `serverspec` is better choice for testing cookbooks than `busser` verifier + `busser-serverspec`.
So I am preparing the document for translation from`busser` verifier + `busser-serverspec` to `shell-verifier` + `serverspec`.
If the document is prepared, I will put link to it in README.

**Comment by cl-lab-k** [comment]
https://github.com/test-kitchen/busser-serverspec#-notice
