### ISSUE TITLE
Allow testing using the ssh driver

### ISSUE THREAD

**Issue by thedrow** [test-kitchen/busser-serverspec#41]
I don't always want to require Chef Omnibus to be installed and it is certainly possible to test with server spec using the ssh driver.
Can we support it as well?

**Comment by cl-lab-k** [comment]
you can use `shell verifer` instead of `busser`, it lets serverspec run with ssh mode.

* https://github.com/test-kitchen/test-kitchen/pull/741 (it has been merged TK 1.5)
* https://rubygems.org/gems/kitchen-verifier-shell (if you use TK 1.4, install gem)

here is my `shell verifer` and `serverspec` example:
https://github.com/cl-lab-k/apache2-take/tree/shell_verifier

**Comment by thedrow** [comment]
Thanks!
Should we support it in this package?
If not we should provide an example in the README.

**Comment by cl-lab-k** [comment]
I have no plan to make any drastic changes to `busser-serverspec`.
And I think `shell-verifier` + `serverspec` is better choice for testing cookbooks than `busser` verifier + `serverspec`.
So I am preparing the document for translation from`busser` verifier + `busser-serverspec` to `shell-verifier` + `serverspec`.
If the document is prepared, I will put link to it in README.

**Comment by cl-lab-k** [comment]
https://github.com/test-kitchen/busser-serverspec#-notice
